### ISSUE TITLE
Need help in  tutorial_word2vec_basic.py

### ISSUE THREAD

**Issue by aMarry** [tensorlayer/tensorlayer#478] opened 2018-04-09 14:12 UTC
I can not save the model with NPZ file. 
with is shown as follows:
  ## could not broadcast input array from shape (50000,128) into shape (50000)

when I run this code :tl.files.save_npz(emb_net.all_params, name=model_name+'.npz')

what's more  i do not konw how to set the label :help wanted  😿

**Comment by DEKHTIARJonathan** [comment] 2018-05-17 10:53
Duplicate of #476

**Closed by DEKHTIARJonathan** 2018-05-17 10:53 UTC
