### ISSUE TITLE
tutorial_bipedalwalker_a3c_continuous_action.py not convergence

### ISSUE THREAD

**Issue by EnricoBeltramo** [tensorlayer/tensorlayer#649] opened 2018-05-26 00:07 UTC
I tryed to launch the demo tutorial_bipedalwalker_a3c_continuous_action.py, but I have a very low convergence (best result: reward: -5.1 | running_reward: -5.6 either after 40000 iteration). In simulation it fall almost immediately. There is some parameters to tune?

**Comment by DEKHTIARJonathan** [comment] 2018-05-26 00:10
@zsdonghao who can be relevant for RL? I can't be of any help on this topic

**Comment by EnricoBeltramo** [comment] 2018-05-26 21:09
I tried the original implementation of the author (https://github.com/MorvanZhou/Reinforcement-learning-with-tensorflow/blob/master/experiments/Solve_BipedalWalker/A3C.py) and it looks to work. May be the issue is the porting on tensorlayer

**Comment by EnricoBeltramo** [comment] 2018-05-28 17:13
> @zsdonghao who can be relevant for RL? I can't be of any help on this topic

I supposed that if a porting on tensorlayer of a working example don't work, may be there is some issue related to library. If is not considered relevant, should be closed.

**Comment by zsdonghao** [comment] 2018-05-28 20:08
@EnricoBeltramo sorry for the late reply, actually, I tested it today, but I found that both TL code and the original implementation cannot converge ... 😢 (under the lastest TL and TF 1.7)

**Comment by DEKHTIARJonathan** [comment] 2018-05-28 20:44
@zsdonghao can you try with an old TL + TF version?

**Comment by zsdonghao** [comment] 2018-05-29 23:49
previously it works very well, that should be a problem, and I guess the problem is related to the sampling part.

**Comment by DEKHTIARJonathan** [comment] 2018-05-30 00:00
What about TL 1.7.4 and TF 1.8.0 ?

**Comment by EnricoBeltramo** [comment] 2018-06-01 17:14
What is the last working version tested on?

**Comment by zsdonghao** [comment] 2018-06-01 18:33
According to the release https://github.com/tensorlayer/tensorlayer/releases?after=1.6.6

it was working on TL 1.6.0

**Comment by DEKHTIARJonathan** [comment] 2018-06-01 19:46
We can easily try and see what changed. Who designed this tutorial ?

**Comment by patchaaquatica** [comment] 2018-06-10 10:48
Hi, just wondering if there has been any development with this issue?  I've reverted back to TF 1.0 with no TL for my research now (i.e. the authors original implementation), but of course would much rather be using up to date versions of TF and TL!

**Comment by DEKHTIARJonathan** [comment] 2018-06-10 17:09
We are investigating it. The error may come from TF not TL.

If you have any idea, we would be glad to receive any PR

**Comment by EnricoBeltramo** [comment] 2018-06-12 11:21
I observed (using a few different model) that if I introduce mechanism like semaphores in order to synchronize the update of weights between threads and common network, the convergence improve. Should be an issue of multithreading?

**Comment by zsdonghao** [comment] 2018-06-13 11:03
The original author of A3C update his code to TF1.8

https://github.com/MorvanZhou/Reinforcement-learning-with-tensorflow/commit/682e89bd7f00b7c2b3598a7bb5975598def9e4cf#diff-2202f4dab91d61358d9ac9058a499562

**Comment by zsdonghao** [comment] 2018-09-30 09:57
fixed. 
I close this issue, feel free to reopen it if you want to discuss.

**Closed by zsdonghao** 2018-09-30 09:57 UTC
Labels: bug, help_wanted
