### ISSUE TITLE
Refactor READMD.md

### ISSUE THREAD

**Issue by lgarithm** [tensorlayer/tensorlayer#646] opened 2018-05-22 14:13 UTC
### New Issue Checklist

- [x] I have read the [Contribution Guidelines](https://github.com/tensorlayer/tensorlayer/blob/master/CONTRIBUTING.md)
- [ ] I searched for [existing GitHub issues](https://github.com/tensorlayer/tensorlayer/issues)

### Issue Description

[INSERT DESCRIPTION OF THE PROBLEM]

Our **README.md** is too large, we need to reorganise the content. Move specific topic to dedicated files, and only keep links on **README.md**

**Comment by DEKHTIARJonathan** [comment] 2018-05-22 14:15
Duplicate of #639

**Closed** 2018-05-22 14:17 UTC
Labels: discussion, documentation, duplicate, help_wanted
