### ISSUE TITLE
Should change np.hstack to np.vstack.

### ISSUE THREAD

**Issue by masonwang513** [tensorlayer/tensorlayer#565] opened 2018-05-13 10:32 UTC
https://github.com/tensorlayer/tensorlayer/blob/4db0b9f52f629742967eb05e3ddb1a23a5ca666f/tensorlayer/utils.py#L323

**Comment by DEKHTIARJonathan** [comment] 2018-05-14 08:36
Closing, duplicate of #288

**Closed by DEKHTIARJonathan** 2018-05-14 08:36 UTC
