### ISSUE TITLE
travis CI is failing for python 3.6

### ISSUE THREAD

**Issue by lgarithm** [tensorlayer/tensorlayer#291] opened 2018-01-28 07:32 UTC
```
[0K$ python tests/test_mnist_simple.py
RuntimeError: module compiled against API version 0xc but this version of numpy is 0xb
ImportError: numpy.core.multiarray failed to import
ImportError: numpy.core.umath failed to import
ImportError: numpy.core.umath failed to import
2018-01-28 07:25:15.979559: F tensorflow/python/lib/core/bfloat16.cc:664] Check failed: PyBfloat16_Type.tp_base != nullptr 
/home/travis/.travis/job_stages: line 57:  2492 Aborted                 (core dumped) python tests/test_mnist_simple.py

travis_time:end:13603272:start=1517124314833580397,finish=1517124316123755764,duration=1290175367
[0K
[31;1mThe command "python tests/test_mnist_simple.py" exited with 134.[0m

Done. Your build exited with 1.
```

**Comment by jart** [comment] 2018-01-30 05:29
Are you on TF 1.5? This might be a dupe of https://github.com/tensorflow/tensorflow/issues/16488

**Comment by lgarithm** [comment] 2018-01-30 07:14
We run `pip install tensorflow` in `.travis.yml` without specific version, so it should be TF 1.5 now.

**Closed** 2018-02-18 14:13 UTC
